name: Deploy to Production

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: myip

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        file: ./Dockerfile
        tags: |
            ttl.sh/${{ env.IMAGE_NAME }}:1h
